name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    container: jssoft/node_browsertests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: node index.js --if-possible
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
