name: Test

on:
  push:
    branches-ignore: [main]

permissions:
  contents: read

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: bash .ci/runChecks.sh
